version: '3'
services:
  ewd-pyspark-jupyter:
    image: easewithdata/pyspark-jupyter:3.5.5
    container_name: ewd-pyspark-jupyterlab
    ports:
        - 8888:8888
        - 4040:4040
        - 4041:4041
    environment:
        JUPYTER_PORT: 8888
        SPARK_UI_PORT: 4040
    volumes:
        - spark_data:/data:rw
  ewd-spark-master:
    image: easewithdata/spark-master:3.5.5
    #command: ln -s /usr/bin/python3 /usr/local/bin/python
    container_name: ewd-spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - 15002:15002
      - 4050:4050
    environment:
      - INIT_DAEMON_STEP=setup_spark
    volumes:
        - spark_data:/data:rw

  ewd-spark-worker-1:
    image: easewithdata/spark-worker:3.5.5
    #command: ln -s /usr/bin/python3 /usr/local/bin/python
    container_name: ewd-spark-worker-1
    depends_on:
      - ewd-spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://ewd-spark-master:7077"
    volumes:
        - spark_data:/data:rw
  ewd-spark-worker-2:
    image: easewithdata/spark-worker:3.5.5
    #command: ln -s /usr/bin/python3 /usr/local/bin/python
    container_name: ewd-spark-worker-2
    depends_on:
      - ewd-spark-master
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=spark://ewd-spark-master:7077"
    volumes:
        - spark_data:/data:rw
volumes:
  spark_data:
